language: csharp
solution: StardewModding.sln
install:
  - nuget restore StardewModding.sln
  - nuget install NUnit.Console -Version 3.9.0 -OutputDirectory testrunner
script:
  - msbuild /p Configuration=Release StardewModding.sln
  - mono ./testrunner/NUnit.ConsoleRunner.3.9.0/tools/nunit3-console.exe ./HarderBetterFasterStrongerAutomate.UnitTest/bin/ReleaseHarderBetterFasterStrongerAutomate.UnitTest.dll